# Site Settings
title: "Sreenivasulu R Portfolio"
description: "Showcasing my skills, projects, and experience in Cloud and DevOps engineering."
url: "https://sreenu827.github.io/sreenivasuluramanaboina"
baseurl: "" # Leave blank unless the site is in a subdirectory

# Author Settings
author:
  name: "Sreenivasulu Ramanaboina"
  email: "sreenu.ramanaboina@gmail.com"
  github: "https://github.com/sreenu827"
  linkedin: "https://www.linkedin.com/in/sreenivasuluramanaboina/"
  location: "Cape Girardeau, MO, USA"
  tagline: "Aspiring Cloud & DevOps Engineer | Automation Enthusiast"

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes" # Correct way to use Minimal Mistakes with GitHub Pages
theme: null # Must be null if using a remote theme

# Footer
footer:
  content: "Built with ❤️ by Sreenivasulu Ramanaboina using Jekyll & GitHub Pages."

# Plugins (Ensure required plugins are included)
plugins:
  - jekyll-remote-theme # Required for using remote themes
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Markdown Options
markdown: kramdown
highlighter: rouge
