# Site Settings
title: "Sreenivasulu R Portfolio"
description: "Showcasing my skills, projects, and experience in Cloud and DevOps engineering."
url: "https://sreenu827.github.io/sreenivasuluramanaboina/"
baseurl: "" # Leave blank unless you need a subdirectory

# Author Settings
author:
  name: "Sreenivasulu Ramanaboina"
  email: "sreenu.ramanaboina@gmail.com"
  github: "https://github.com/sreenu827"
  linkedin: "https://www.linkedin.com/sreenivasuluramanaboina/"
  location: "Cape girardeu"
  tagline: "Aspiring Cloud & DevOps Engineer | Automation Enthusiast"

# Theme Settings
theme: "minimal-mistakes-jekyll" # Replace with the theme you're using
remote_theme: "mmistakes/minimal-mistakes" # Optional if using a remote theme

# Footer
footer:
  content: "Built with ❤️ by Sreenivasulu R using Jekyll & GitHub Pages."

# Plugins (Optional)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Markdown Options
markdown: kramdown
highlighter: rouge
